### ISSUE TITLE
Contextual Menu opening don't work with space separated files

### ISSUE THREAD

**Issue by vhanla** [EtheaDev/MarkdownShellExtensions#1]
I tried opening a markdown file with contextual menu and it fails.
![imagen](https://user-images.githubusercontent.com/1015823/132255468-e70b6349-b67b-4a61-901f-7da25c4b8193.png)
As you can see, it shows "TODO" but the filename is "TODO list.md".

**Comment by carloBarazzetta** [comment]
If you open-it directly from the Editor, it works?

**Comment by vhanla** [comment]
Yes, it opens. However, there seems to be a SynEdit issue opening cp1252 encoding. 
![imagen](https://user-images.githubusercontent.com/1015823/132267432-5e3d3167-49c3-460c-b401-c0f69a4140b4.png)
But that's not related to this issue, and it works with UTF-8 encoding files and most of the other files.

**Comment by carloBarazzetta** [comment]
Can you attach here the file for testing? Thanks.

**Comment by vhanla** [comment]
Here you are. 
It can't open if filenames has special chars, also in content.
[español.zip](https://github.com/EtheaDev/MarkdownShellExtensions/files/7122714/espanol.zip)
