### ISSUE TITLE
Open With Markdown File Editor Fails

### ISSUE THREAD

**Issue by Kamek437** [EtheaDev/MarkdownShellExtensions#11]
Windows 11, just installed and the preview works good and a lot faster than the others I have tried but when I right click a markdown file and hit Open With "Markdown File Editor" it says "Markdown File Editor not found". I would assume it is supposed to open in the bundled MDTextEditor.exe right?

**Comment by carloBarazzetta** [comment]
Yes, there is an error. I'll investigate for the problem. You can also use "open as..." windows menu to associate .md extensions to the editor...

**Comment by Kamek437** [comment]
Thanks! Great product by the way, it has better markdown preview than microsoft powertools.

**Comment by leConce** [comment]
> it has better markdown preview than microsoft powertools.

Hi!
Could not have the markdown preview to work.
It only shows an icon on the preview pane.

![image](https://github.com/user-attachments/assets/8cae8788-9e93-4208-970e-8333edc7d2af)

but all other files preview work fine as this .txt example

![image](https://github.com/user-attachments/assets/8322e897-cfe5-4a1a-b261-ba361ff83508)

*.rtf *.doc, Excel spreadsheets, all appear well on the preview pane. Just *.md files don't.
And MD fileeditor is the default program to open *.md files

![image](https://github.com/user-attachments/assets/a13a3465-7c62-4fb5-b241-4b1d12feb9d8)

Can you please help me to get MD files preview?

BTW
Maybe it was already solved but the `open with...` works fine in my Windows 11.

**Comment by carloBarazzetta** [comment]
Sorry but I've no problem in my PC:
![image](https://github.com/user-attachments/assets/7056d654-bdf9-4831-acfa-967054837f20)
Try to uninstall, then clean manually C:\Program Files\Ethea\MDShellExtensions\MDShellExtensions.dll, then reinstall product.
Check if the C:\Program Files\Ethea\MDShellExtensions\MDShellExtensions.dll is of the correct version (2.3.1)

**Comment by leConce** [comment]
Thanks carloBarazzetta
It works fine.

I've done all these steps from my Admin user account just in case 😊
Maybe that was my first mistake.
I think I've just installed `MarkdownShellExtensions` from my normal user account.

I was looking for a Windows Explorer .md files preview for a long time.
Thanks for your reply.

**Comment by carloBarazzetta** [comment]
I'm glad you solved the problem. Also try the editor, it's very convenient, I use it every day to update the documentation of my projects. If you are also a Delphi developer you can also use the MarkDownHelpViewer project to integrate Help into the application using the markdown format.
