### ISSUE TITLE
Windows 7 error

### ISSUE THREAD

**Issue by Sippelin** [EtheaDev/MarkdownShellExtensions#4]
Hi! Just installed MDShellExtensionsSetup.exe on my Windows 7 (64bit) SP1 and have an error when try to open preview in explorer:

> Problem signature:
> Problem Event Name: APPCRASH
> Application Name: prevhost.exe
> Application Version: 6.1.7601.17562
> Application Timestamp: 4d5e2495
> Module name with error: KERNELBASE.dll
> Module version with error: 6.1.7601.24545
> Module timestamp with error: 5e0eb6bd
> Exception Code: c06d007f
> Exception Offset: 000000000000b87d
> OS Version: 6.1.7601.2.1.0.256.48
> Language Code: 1049
> Additional information 1: 0ffe
> Additional Information 2: 0ffeff344546bd9ed3a4409568c50c90
> Additional information 3: 63bc
> Additional Information 4: 63bcffb11abe9078ffd9d7b03d16c883

If i try to click on .md file in a preview window this error: 

> It is not possible to preview this file due to an error in Delphi Markdown Preview Handler

What i do wrong?

**Comment by carloBarazzetta** [comment]
Try opening the same file using the MarkDown file editor, see if the same error is thrown, and give me feed-back.
Does the error occur for every .md file or just one?

**Comment by Sippelin** [comment]
If i try to open .md with file editor everything is fine. File editor works good. This error occurs with every md file only with preview.

**Comment by carloBarazzetta** [comment]
I suppose it's a problem with Windows 7 - SP1... I've tested the preview only with Windows 10 and 11...
You can try another ShellExtensions of mine, like [https://github.com/EtheaDev/SVGShellExtensions](url)
to see if the problem is at "low level" of every Extensions or only affected by MarkDownShellExtensions...

**Comment by carloBarazzetta** [comment]
No more feedback.
