### ISSUE TITLE
Viewing and Editing File Metadata YAML

### ISSUE THREAD

**Issue by A-N-P** [EtheaDev/MarkdownShellExtensions#5]
I do not know if my question can be translated correctly by a translator, and I do not know if it is possible to do this at all, but I could not help but write this here.
It would be useful to be able to edit at least a limited number of YAML parameters from third-party file managers. And of course, output some parameters to the columns of file managers for sorting *.md files. At least, the title, tags, comments, description. Perhaps Markdown Shell Extensions will be able to solve this...

Thank you!

**Comment by carloBarazzetta** [comment]
Sorry but this request is out of scope of this project.
