### ISSUE TITLE
Editor markdown preview not support Chinese？

### ISSUE THREAD

**Issue by pascalcn** [EtheaDev/MarkdownShellExtensions#6]
Editor preview has display problem of Chinese Characters.

Editor preview not support Chinese。

eg：

举例。

**Comment by carloBarazzetta** [comment]
Please send me an example of the problem or a chinese markdown file to make a test...

**Comment by carloBarazzetta** [comment]
Fixed in 2.2.1 version.

**Comment by pascalcn** [comment]
thank you

**Comment by carloBarazzetta** [comment]
In 2.2.2 version I've fixed it also in Explorer Preview Panel.
