### ISSUE TITLE
Errore di runtime durante l'installazione

### ISSUE THREAD

**Issue by shineworld** [EtheaDev/MarkdownShellExtensions#7]
Versione 2.2.2 su W10 Professional.

Verso la fine dell'installazione ottengo "Errore di runtime" come da immagine:
![image](https://github.com/EtheaDev/MarkdownShellExtensions/assets/1633598/db886317-12db-4093-b0a4-05e2d63d9078)

**Comment by carloBarazzetta** [comment]
Purtroppo non mi dice granché: che versione stai installando?
Sembra un problema quando tenta di registrare la dll, ho provato su un'altra macchina e lo ha dato anche a me, eppure il viewer mi mostrava l'anteprima, quindi sembra che la dll l'abbia registrata comunque. Poi ho disinstallato e reinstallato e non mi ha dato più errore...

**Comment by shineworld** [comment]
Sto provando l'ultima versione presente in questo Git su W10.
A parte la segnalazione d'errore l'editor funziona ma l'anteprima no.
Proverò a ripetere l'installazione :)
Grazie del supporto.

**Comment by carloBarazzetta** [comment]
Prova a riavviare la macchina se l'anteprima non va... Hai per caso installato altri viewer per markdown?

**Comment by carloBarazzetta** [comment]
Feedback?

**Comment by shineworld** [comment]
Ho disinstallato e durante la disinstallazione ha dato ancora l'errore.
Ho provato a reinstallare e stessa cosa.
L'editor chiamato direttamente funziona bene.
L'estensione non viene registrata.

Attualmente ho installato l'estensione per WinMerge, TortoiseGit, e l'estensione per SvgShellExtensions (Angusj).
Almeno queste so di averle fatte, perché se altri pacchetti hanno installato estensioni è accaduto senza che ne fossi consapevole.

Visualizzatore di Eventi ha registrato questo:
`Nome dell'applicazione che ha generato l'errore: regsvr32.exe, versione: 10.0.19041.1, timestamp: 0xc2fd4602
Nome del modulo che ha generato l'errore: MDShellExtensions.dll, versione: 2.2.2.0, timestamp: 0x663dc954
Codice eccezione: 0xc0000005
Offset errore 0x000000000000ef99
ID processo che ha generato l'errore: 0x4b28
Ora di avvio dell'applicazione che ha generato l'errore: 0x01daacd60b2dfcc4
Percorso dell'applicazione che ha generato l'errore: C:\WINDOWS\system32\regsvr32.exe
Percorso del modulo che ha generato l'errore: C:\Program Files\Ethea\MDShellExtensions\MDShellExtensions.dll
ID segnalazione: 394e6e43-07b7-4768-8ba4-44034503bfb5
Nome completo pacchetto che ha generato l'errore: 
ID applicazione relativo al pacchetto che ha generato l'errore: `

`[-](https://github.com/EtheaDev/MarkdownShellExtensions/issues/7#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/EtheaDev/MarkdownShellExtensions/issues/7#) <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2024-05-23T05:57:07.3122748Z" /> 
  <EventRecordID>101057</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>ID547.qem.local</Computer> 
  <Security /> 
  </System>
[-](https://github.com/EtheaDev/MarkdownShellExtensions/issues/7#) <EventData>
  <Data>regsvr32.exe</Data> 
  <Data>10.0.19041.1</Data> 
  <Data>c2fd4602</Data> 
  <Data>MDShellExtensions.dll</Data> 
  <Data>2.2.2.0</Data> 
  <Data>663dc954</Data> 
  <Data>c0000005</Data> 
  <Data>000000000000ef99</Data> 
  <Data>4b28</Data> 
  <Data>01daacd60b2dfcc4</Data> 
  <Data>C:\WINDOWS\system32\regsvr32.exe</Data> 
  <Data>C:\Program Files\Ethea\MDShellExtensions\MDShellExtensions.dll</Data> 
  <Data>394e6e43-07b7-4768-8ba4-44034503bfb5</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>`

**Comment by carloBarazzetta** [comment]
Sto avendo lo stesso problema su un altra macchina... molto strano.
comunque se vuoi una estensione per SVG un po' più evoluta di quella di AngusJ c'è:
https://github.com/EtheaDev/SVGShellExtensions
che contiene anche un comodo editor ;-)

**Comment by carloBarazzetta** [comment]
Ho preparato un nuovo setup, fammi sapere se ora è risolto... a me ha funzionato.
