### ISSUE TITLE
Can't rebuild MDTextEditor project

### ISSUE THREAD

**Issue by wmeyer48** [EtheaDev/MarkdownShellExtensions#8]
Hello,
I was looking at your MarkDown code, and tried to build the MDTextEditor projecy in Delphi 12.1. It complains that there a properties missing from SynXMLSyn.Options. In fact, there is no Options property in SynXMLSyn that I can see. I would like to make use of this, but have no idea how to proceed on that.
Also, FrameEditor12 is given in a dpk file as a required module, but FrameEditor has no version suffix.
I realize that I can use the one available through the installer, but for the app I have in mind, it would be much better if I could integrate it.

Thanks!

**Comment by carloBarazzetta** [comment]
Take care that you don't have the same versions of SynEdit and HTMLViewer installed in your IDE, compared to the version contained into \Ext\ Folder.
Now I've committed a new version, adding Packages folder for external libraries, so you can upgrade you components into IDE build/installing the packages and recompile the Editor without problems... 

Please give me a feed-back

**Comment by carloBarazzetta** [comment]
No feedback, issue closed...
